### ISSUE TITLE
Update the rubygem at rubygems.org

### ISSUE THREAD

**Issue by andywenk** [cescue/json_to_csv#3]
Hey Chris,

thanks for accepting the PR. It would be super awesome if you have the time to also build a new version of the gem. Do you need any assistance?

https://rubygems.org/gems/json_converter

Thanks and all the best

Andy

**Comment by cescue** [comment]
Done. Let me know if the new release doesn't work as expected.

https://rubygems.org/gems/json_converter/versions/0.0.1

Thanks!
